### ISSUE TITLE
Hypertabs cleanup

### ISSUE THREAD

**Issue by luphoria** [TerbiumOS/webOS#10]
https://github.com/B3ATDROP3R/Hypertabs
**TODO**: have Hypertabs follow theming
**TODO**: clean up garbage for both Terbium and Hypertabs, so we only package what we need
**TODO**: add bookmarks bar to newwin.html
**TODO**: do not open pinned tabs on new window if Hypertabs is already running

**Comment by vukle** [comment]
could you explain why?

**Comment by luphoria** [comment]
> could you explain why?

Hypertabs is a fully featured HTML5 browser, including a proper tabbed system, and easy implementation of bookmarks, pinning tabs, and other features. The Terbium browser is...not. Hypertabs is an improvement in every way, even as-is (right now, at which point it isn't really integrated to webOS).

**Comment by luphoria** [comment]
Repurposing this issue for the Hypertabs merge TODOs.
