### ISSUE TITLE
None of the apps load

### ISSUE THREAD

**Issue by pandadevv5495** [TerbiumOS/webOS#22]
When hosting, the browser, vscode, etc wont load at all.

**Comment by NovaAppsInc** [comment]
What version are you on, also what error do you get in the console?

**Comment by rusdevofficial** [comment]
I'm also having this error, it says not found... It can load every app that isn't part of 
[Screen recording 2023-01-23 13.40.52.webm](https://user-images.githubusercontent.com/63070424/214122817-2001a5e9-6aa4-4923-be57-45ba56506af7.webm)
The recording above was performed on ChromeOS Version 107.0.5304.110 (Official Build) (64-bit).

https://user-images.githubusercontent.com/63070424/214124016-9d056d45-8099-4368-b100-5247b8c493b8.mp4

The recording above was performed on  Chrome 108 on Windows 10. (Manual Selenium Testing)

**Comment by rusdevofficial** [comment]
It seems the problem is worst on Chrome, but you do seem to be having an API issue.

**Comment by NovaAppsInc** [comment]
> It seems the problem is worst on Chrome, but you do seem to be having an API issue.

The API "issue" on browser is not my problem as it feeds through a decentralized search engine

also for some reason the Service Worker isn't registering on `terbiumux.net`

**Comment by pandadevv5495** [comment]
Now I just checked again now its this error:

RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

**Comment by pandadevv5495** [comment]
Most recent version

**Comment by NovaAppsInc** [comment]
> Now I just checked again now its this error:
> 
> RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

I literally said the service worker is not being registered on other domains other than `terbium.ga` I literally looked
