### ISSUE TITLE
Proxy does not work.

### ISSUE THREAD

**Issue by Thesecondalthowcool** [TerbiumOS/webOS#32]
When ever I used terbium, the proxy/apps never work. If this is an issue you are already trying to fix, let me know. If not, please fix the issue.

**Comment by GamerGoat112** [comment]
That's the issue I am having as well.

**Comment by Notplayingallday383** [comment]
In #21 it mentions this error but it isn't a great solution but ig you could try it or wait for a patch

**Comment by Notplayingallday383** [comment]
Forgot to mention this is fixed now
