### ISSUE TITLE
Icons not showing up when adding custom apps

### ISSUE THREAD

**Issue by Notplayingallday383** [TerbiumOS/webOS#33]
Recently I have been experiencing this issue when adding new apps to Terbium where the icons don't load when launching the app and was wondering if anyone knew a fix.
![image](https://user-images.githubusercontent.com/72810050/234844042-f44b7d1b-dc6b-445a-9059-37e89becc5e7.png)

**Comment by NovaAppsInc** [comment]
Mind sending me the line that initializes the window manager to open the app?
