### ISSUE TITLE
how to make a deploy

### ISSUE THREAD

**Issue by vresade** [TerbiumOS/webOS#34]
I'm trying to deploy but I can't get a domain to create

**Comment by Notplayingallday383** [comment]
Do you mean like a place you can run it on such as Cloudflare pages or replit?

**Comment by ro2alive** [comment]
> Do you mean like a place you can run it on such as Cloudflare pages or replit?

Nah, he means that on freenom, it won't let him search for a domain, it won't let me do the same.

**Comment by Xtendera** [comment]
> > Do you mean like a place you can run it on such as Cloudflare pages or replit?
> 
> Nah, he means that on freenom, it won't let him search for a domain, it won't let me do the same.

The issue is super simple to fix, just search for your domain in incognito with the ending as well (so if you want a domain like example.tk, then you would just type example.tk). This worked for me.
