### ISSUE TITLE
[Feature Request] About Page in Settings & UV and Ruffle Update

### ISSUE THREAD

**Issue by Notplayingallday383** [TerbiumOS/webOS#35]
Hi, I was wondering if for the terbium settings app there could be kind of like a windows about page with the version and maybe credits, and also a fix/update to UV to fix this range error with the SW or potentially an upgrade to the New Ultraviolet. Thanks

**Comment by Notplayingallday383** [comment]
I wanted to add ruffle to this list

**Comment by Notplayingallday383** [comment]
I have created a implementation of the about page however it doesn't seem to work any thoughts?
`<div class="cat aboutView" view="about" hiddenCat="true">
                <div class="title">
                    <h3>About</h3>
                    <div class="border-bottom"></div>
                </div>
                <div class="info">
                    <p>Terbium WebOS</p>
                    <p>Version: 1.43</p>
                    <p>Developer: SNOOT</p>
                    <p>(C) Copyright 2023 All Rights Reserved</p>
                    <p>Licensed Under the <a href="https://github.com/TerbiumOS/webOS/blob/main/LICENSE">Apache 2.0 License</a></p>
                </div>
            </div>`

**Comment by NovaAppsInc** [comment]
I had an about page that; I didn't remove it though it was just lost to the ether and blah blah blah as I won't get into it😓

**Comment by Notplayingallday383** [comment]
ah lol
