### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kyokuchi** [TerbiumOS/webOS#39]
404 Not Found nginx/1.18.0 (Ubuntu)

**OS Version and platform info**
-https://terbiumux.net/
- Won't say
- Chrome

**Additional context**
nothing works

**Comment by Notplayingallday383** [comment]
This is a issue with the Bare or the public link

**Comment by Notplayingallday383** [comment]
You can try https://terbium-webos.pages.dev see if that works
