### ISSUE TITLE
Cloudfare is down on the "terbium.motortruck1221.tech" domain.

### ISSUE THREAD

**Issue by huxtabl8** [TerbiumOS/webOS#4]
Web server is down `Error code 521`
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=terbium.motortruck1221.tech) for more information.
2022-09-16 12:47:05 UTC

**Comment by huxtabl8** [comment]
Invalid SSL certificate Error code 526
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_526&utm_campaign=terbium.motortruck1221.tech) for more information.
2022-09-21 13:16:15 UTC

**Comment by GamerGoat112** [comment]
Did you get it figured out?
