### ISSUE TITLE
Deploy options

### ISSUE THREAD

**Issue by Thesecondalthowcool** [TerbiumOS/webOS#41]
What is the build and start command? It's possible to deploy. Found a link that is hosted on Render

**Comment by Notplayingallday383** [comment]
its `npm install` to install the depencencies needed and then run `npm start` to start the http server which is localhost:6969. Yes it is possible to deploy it to something such as render just set the build command to `npm install` and start to `npm start`

**Comment by Thesecondalthowcool** [comment]
ive tried that bruv

**Comment by Thesecondalthowcool** [comment]
now it works
