### ISSUE TITLE
Server isnt a constructor (v1.41)

### ISSUE THREAD

**Issue by TheSman122333** [TerbiumOS/webOS#42]
const bare =  new Server('/bare/', '');
              ^

TypeError: Server is not a constructor
    at file:///home/runner/TeemingArcticPorts/index.mjs:6:15
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)

OS version 1.41 I think, I made a fork of terbium a looong time ago, and I recovered it. Using Opera GX/Chrome

The issue is that there is no output in the repls saying that server isnt a constructor, but in 1.41, and 1.42 it uses the code that gives the error

this code: import Server from 'bare-server-node';
import http from 'http';
import nodeStatic from 'node-static';

const bare =  new Server('/bare/', '');
const serve = new nodeStatic.Server('static/');

const server = http.createServer();

server.on('request', (request, response) => {
    if (bare.route_request(request, response)) return true;
    serve.serve(request, response);
});

server.on('upgrade', (req, socket, head) => {
	if(bare.route_upgrade(req, socket, head))return;
	socket.end();
});

server.listen(process.env.PORT || 6969);

**Comment by Notplayingallday383** [comment]
Did you run npm i?

**Comment by Notplayingallday383** [comment]
Did you run it?

**Comment by TheSman122333** [comment]
So sorry, I do not know what happened, but it worked for a while, and then again its back to not working.

**Comment by TheSman122333** [comment]
I am also using bare server latest (2.01)
