### ISSUE TITLE
Broswer doesn't work

### ISSUE THREAD

**Issue by KanekiHits** [TerbiumOS/webOS#47]
it doesn't work

**Comment by scatcat5isdead** [comment]
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by Notplayingallday383** [comment]
Thats usually a issue communicating to the bare. What site are you using?

**Comment by scatcat5isdead** [comment]
it seems fixed on your site but i hosted it on cloudflare and i get the above error

**Comment by dt5093** [comment]
i am having a bare issue
Error: Unable to fetch Bare meta: 404
