### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by strmcnx** [TerbiumOS/webOS#48]
**Error Code and/or Error Message**
Error: ENOENT: no such file or directory, stat '/home/travel2fiadmin/webOS/static/sw/hvtrs8/-tkkvoi.aoo'
This is with all the apps preinstalled.

**Screenshots**
![image](https://github.com/TerbiumOS/webOS/assets/46403488/e251f976-8ae0-4c98-86c1-8e64be316c1d)

**OS Version and platform info**
- Site you used: http://travel2fi.local:6969/ (Do not click as this is local)
- Version on the bottom left of screen: 143
- Browser: Chrome (Raspberry Pi 4B as server)

**Additional context**
No additional Context provided.

**Comment by Notplayingallday383** [comment]
This is an issue with the service worker which was present in older versions of 1.43 try updating your deployment and it should work

**Comment by Notplayingallday383** [comment]
@strmcnx hey just following up, do you still need assistance?

**Comment by strmcnx** [comment]
Sorry for the delay @Notplayingallday383 that fixed my problem. Thanks.
