### ISSUE TITLE
Given error code when deplying with cloudflare

### ISSUE THREAD

**Issue by ghost** [TerbiumOS/webOS#50]
I deployed using cloudflare using a set of inscturtions.. somewhere here and whenever I tried to access https://discord.com/channels/@me using the BruhProxy app, I get a TypeError
![Screenshot 2023-11-29 11 13 21 AM](https://github.com/TerbiumOS/webOS/assets/68405486/500499fc-0cc2-4357-af50-88c806b0333b)
![Screenshot 2023-11-29 11 15 57 AM](https://github.com/TerbiumOS/webOS/assets/68405486/5d0b9eb7-72f3-4a28-827b-82cf9df7ef06)

The domain I made is https://stardust-8sk.pages.dev/

**Comment by Notplayingallday383** [comment]
Sorry for the late response but you need to change the bare since the one you may be using could be blocked or down
