### ISSUE TITLE
the static proxy doesnnt work

### ISSUE THREAD

**Issue by TrapjawwS** [TerbiumOS/webOS#57]
yeah the static proxy doesnt work. I'm using chrome. But yeah here's a screenie

![image](https://github.com/TerbiumOS/webOS/assets/145371179/c7d00525-601d-4a53-b79d-979121da3e57)

**Comment by Notplayingallday383** [comment]
since I see the little version string in the corner, this is a old version of terbium so try updating terbium to see if it still does that
