### ISSUE TITLE
Issue With Ultra Violet and /bare/ server node.

### ISSUE THREAD

**Issue by PrimeKidMN** [TerbiumOS/webOS#62]
<img width="650" alt="Screenshot 2024-03-20 102743" src="https://github.com/TerbiumOS/webOS/assets/135172681/932e3ee0-f1e4-43d5-ad1b-48bfddc2270b">

I have no idea how to trouble shoot this and if need please fix it but if its on my end someone please tell me and provide instructions on what to do.

**Comment by Notplayingallday383** [comment]
hey there, Uhh It looks like your on a codespace so I think this is just normal codespace issues with internet access. When you click  the text that says: Bare Server does it bring a page like this? 
![image](https://github.com/TerbiumOS/webOS/assets/72810050/f7a249ac-6ee0-4d60-bb63-71f6fee2cb19)

**Comment by Notplayingallday383** [comment]
> > hey there, Uhh It looks like your on a codespace so I think this is just normal codespace issues with internet access. When you click the text that says: Bare Server does it bring a page like this? ![image](https://private-user-images.githubusercontent.com/72810050/323699206-f7a249ac-6ee0-4d60-bb63-71f6fee2cb19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzUyMjAsIm5iZiI6MTcxMzQ3NDkyMCwicGF0aCI6Ii83MjgxMDA1MC8zMjM2OTkyMDYtZjdhMjQ5YWMtNmVlMC00ZDYwLWJiNjMtNzFmNmZlZTJjYjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIxMTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YzIzMzdhZjNkYThkNTQ3YTY0ZDFiZGRiYTgyOGM3NTFlN2IyMjljNGViOGEzNzVjMDkxYTEzNTIwY2E1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ACwYhMMUriU84ztbalsFFF_GEsjbemo1gWtad-fwmsw)
> 
> The issue is that they have not made it a public link on codespaces

Oh yeah I forgot that was a thing lol

**Comment by ProtonCodespaces** [comment]
I made it public was not fixed

**Comment by nmsjayden** [comment]
The issue i assume is really unfixable unless your admin remove the network proxy

**Comment by Notplayingallday383** [comment]
update terbium perchance. it uses wisp UV now so it should be fixed
