### ISSUE TITLE
Internal Server Error  Code: UNKNOWN "there are no bare clients"

### ISSUE THREAD

**Issue by Nirmata-1** [TerbiumOS/webOS#67]
when I tried using the web browser, I got an error saying there were no bare clients. I deployed using vercel if that matters.
![image](https://github.com/TerbiumOS/webOS/assets/161094919/7a0088d4-5897-4a81-9db2-2d6dfd226e43)
![image](https://github.com/TerbiumOS/webOS/assets/161094919/4c7f8c6d-3d4e-4e38-b7d3-280257fda5f4)

I

**Comment by Notplayingallday383** [comment]
It seems I ended up breaking it so uhh ill release a fix for it in a bit I just have Finals to deal with rn lol

**Comment by Nirmata-1** [comment]
Take your time, I had my finals last month too.

**Comment by Notplayingallday383** [comment]
alrighty this should be resolved now in the [latest commit](https://github.com/TerbiumOS/webOS/commit/dfd22e4671cd85300decdee34740bf4a32c7d5da), however I haven't tested it yet but lmk.

PS. If your wondering I aced my first 3 finals
