### ISSUE TITLE
CNAME record to host on more domains

### ISSUE THREAD

**Issue by GamerGoat112** [TerbiumOS/webOS#7]
just add the CNAME record to your domain and point it to `c.terbium.ga`

_Originally posted by @illusionTBA in https://github.com/TerbiumOS/webOS/issues/3#issuecomment-1248713540_
      I have done this and it shows this.
Error
The requested URL could not be retrieved
Error: The web filter could not find the address for the requested site
Why you are seeing this:
The system is unable to determine the IP address for cliffsnotes.tk

Possible reasons could be:
The site name has been entered incorrectly or does not exist. Please double check you have entered the correct URL.
The Domain Name Server (DNS) is unable to resolve the IP address for this domain.
If this problem persists, please ask your administrator to:
Check your DNS services are operating correctly.

**Comment by illusionTBA** [comment]
the site to point your cname record to is down.

**Comment by GamerGoat112** [comment]
So terbium is down? Or cloudflare? Or Freenom?

**Comment by NovaAppsInc** [comment]
> the site to point your cname record to is down.

no it actually isn't I think people just don't know how to actually work this shit because I have legit use the CNAME on all the restocked domains soooo yeah

**Comment by GamerGoat112** [comment]
Here is a list of exactly what I have done.
1. Get a link from freenom
2. Change nameservers to cloudflare's
3. Add CNAME record of @ --> c.terbium.ga
4. Change SSL/TLS to Full(Strict)

**Comment by GamerGoat112** [comment]
Is it possible that you have only allowed cloudflare connections from yourself?
![image](https://user-images.githubusercontent.com/107008636/193944862-31a2922d-c42e-4da8-821c-73da668c124f.png)
It could be blocking our cloudflare requests.

**Comment by NovaAppsInc** [comment]
No because someone else was able to do it without my assistance.

**Comment by GamerGoat112** [comment]
I'm so confused on what I'm screwing up here then.
