### ISSUE TITLE
Internel Server Error Unknown Failed to Fetch

### ISSUE THREAD

**Issue by code-leech** [TerbiumOS/webOS#72]
This seems to be fixed by refreshing the page but it happens every time I open the page.
I'm using localhost:6969 btw
Oh, and vercel deployment doesn't work, it doesn't give a html file, only index.js

**Comment by Notplayingallday383** [comment]
the hosted port should be working, if it isnt idk what to really tell ya, as for vercel could you share the settings you used to deploy it to vercel?
