### ISSUE TITLE
Error when deployed with codespaces

### ISSUE THREAD

**Issue by om3ga6400** [TerbiumOS/webOS#76]
**Error Code and/or Error Message**
npm error code EJSONPARSE
npm error path /workspaces/webOS/package.json
npm error JSON.parse Expected double-quoted property name in JSON at position 328 while parsing near "...npm\" : \">=8.7.0\",\n  },\n  \"author\": \"snoo..."
npm error JSON.parse Failed to parse JSON data.
npm error JSON.parse Note: package.json must be actual JSON, not just JavaScript.
npm error A complete log of this run can be found in: /home/codespace/.npm/_logs/2024-09-23T13_44_32_526Z-debug-0.log

**Screenshots**
![image](https://github.com/user-attachments/assets/228c86d2-a52d-400c-8694-1d88e91caa0a)

**OS Version and platform info**
- Github Codespaces
- Chrome

**Comment by om3ga6400** [comment]
I got it to deploy to local host by removing the comma on line 14 or package.json

**Comment by Andderemchin** [comment]
Hey I already figured out the comma trick like you did, but for some reason I get an error that says "Cannot GET /sw/hvtrs8%252F-ymuvu%60e,cmm"

**Comment by om3ga6400** [comment]
odd

**Comment by Notplayingallday383** [comment]
> Hey I already figured out the comma trick like you did, but for some reason I get an error that says "Cannot GET /sw/hvtrs8%252F-ymuvu%60e,cmm"

hmm let me look into this

**Comment by Notplayingallday383** [comment]
also I fixed the issue with the NPM engines

**Comment by om3ga6400** [comment]
> also I fixed the issue with the NPM engines

I got a new error now

node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tomphttp/bare-server-node' imported from /workspaces/webOS/index.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by om3ga6400** [comment]
@Notplayingallday383

**Comment by Notplayingallday383** [comment]
alright It should be fixed now. I forgot to update the deps lol

**Comment by Notplayingallday383** [comment]
btw im gonna push out a fix to the proxy tmr so update your fork/instance once I push that (ill mention it in the commit description which makes it show up here)

**Comment by 88411** [comment]
Hey when I tried to deploy on cloudflare I got the same issue. I fixed it by just typing in "npm install"

**Comment by 88411** [comment]
### **Alternative**

1. First fork this repo
2. Then go to Cloudflare.com and sign in
3. Then on the left column select workers and pages
4. After that click on create and then select pages (NOT workers) 
5. Select connect to git and connect your GitHub account.
6. Then select the forked repo and click begin setup.

**These next steps are very important:**

DO NOT touch framework preset.

7. For the build commands, type: "npm install" (The repo says to put "npm install && npm start" however this does not work)
8. For output directory type: "static"
9. Then click save and deploy and cross your fingers that everything goes well

After it builds it will provide you with a link and your good to go.

**Also if for some reason you can't figure it out here is my link I got from following those exact steps
 "https://webos2-d9d.pages.dev/"**
By the time you are reading this it might be blocked tho idk

GL
